### PR TITLE
Fixed #524

### LINKED ISSUE #524: Small inconsistency with your banner
**Describe the bug**
There's a small formatting issue with your banner.

**To Reproduce**
1. `$ git clone https://github.com/RustScan/RustScan`
2. `$ cd RustScan`
3. `$ cargo build`
3. `$ ./target/debug/rustscan`

**Expected behavior**

**Screenshots**
From my terminal (Konsole running Bash (but same effects on VT))
```
[*****@manjaro RustScan]$ ./target/debug/rustscan 
.----. .-. .-. .----..---.  .----. .---.   .--.  .-. .-.
| {}  }| { } |{ {__ {_   _}{ {__  /  ___} / {} \ |  `| |
| .-. \| {_} |.-._} } | |  .-._} }\     }/  /\  \| |\  |
`-' `-'`-----'`----'  `-'  `----'  `---' `-'  `-'`-' `-'
The Modern Day Port Scanner.
________________________________________
: http://discord.skerritt.blog           : <-- this thing
: https://github.com/RustScan/RustScan :
 --------------------------------------
😵 https://admin.tryhackme.com
...
```

**Desktop (please complete the following information):**
 - OS: Manjaro Linux 6.1.44-1-MANJARO
 - Version: Cloned from the repo like 5 minutes ago (so latest).

**Additional context**
I'm not a Rust programmer (I'm a C programmer), but I'll see if I can send you guys a pull request to solve the problem. I know (knew) a little Rust so it won't be too big a hassle (I hope.)

### PR DESCRIPTION
**Pull request by R-Rothrock**
Fixes #524. I realize I've only saved you guys like 5 seconds, but here you go!

### CODE REVIEW

File: src/main.rs [hunk 1]
```diff
@@ -220,7 +220,7 @@ fn print_opening(opts: &Opts) {
     let info = format!(
         "{}\n{}\n{}\n{}",
         r#"________________________________________"#,
-        r#": http://discord.skerritt.blog           :"#,
```
Comment (CMNatic) [inline src/main.rs:223]: Tested locally and yup, formatting is fixed :)

**Review by CMNatic — APPROVED** [review]
PR approved. Thanks for the submission:)
