### PR TITLE
Changed the dns resolving to use std::net::ToSocketAddrs

### LINKED ISSUE #245: DNS Resolver does not use OS' resolver
**Describe the bug**
Per `trust_dns_resolver`'s documentation:
https://docs.rs/trust-dns-resolver/0.19.5/trust_dns_resolver/

> It does not use the Host OS' resolver. If what is desired is to use the Host OS' resolver, generally in the system's libc, then the std::net::ToSocketAddrs variant over &str should be used.

This causes some problems as with CTFs sometimes we have to change our hosts file to reach the target webpage. 

Also, it would be faster to use the OS' resolver than an external one.

### PR DESCRIPTION
**Pull request by shahar481**
* Made trust-dns a fallback resolver if the OS can't resolve

Fixes #245

### CODE REVIEW

File: src/main.rs [hunk 1]
```diff
@@ -283,14 +290,14 @@ fn read_ips_from_file(
 /// Given a string, parse it as an host, IP address, or CIDR.
 /// This allows us to pass files as hosts or cidr or IPs easily
 /// Call this everytime you have a possible IP_or_host
-fn parse_to_ip(address: String, resolver: &Resolver) -> Result<Vec<IpAddr>, std::io::Error> {
```
Comment (niklasmohrin) [inline src/main.rs:286]: This functions signature should also be changed: `address` should be `&str`, because ownership is not needed. The return type should be just the vector as the function always returns `Ok`.

**Review by niklasmohrin — COMMENTED** [review]
Hey there! Thanks for contributing!

Every logic you introduced is correct as I see it. I did however not check whether there are other places that need this addition too yet, but I don't think there are some anyway.

Most of the stuff I suggest are lints from `cargo clippy` or style changes (with performance gains sometimes). Interestingly, most of the things have been here already and are just things that need fixing in general. This PR is a great opportunity to fix these questionable style choices.

**Comment by bee-san** [comment]
@all-contributors please add @shahar481 and @niklasmohrin for code

File: src/main.rs [hunk 2]
```diff
@@ -213,13 +213,13 @@ fn build_nmap_arguments<'a>(
...
         &Resolver::new(ResolverConfig::cloudflare_tls(), ResolverOpts::default()).unwrap();
 
     for ip_or_host in &opts.addresses {
-        match read_ips_from_file(ip_or_host.to_owned(), &resolver) {
+        match read_ips_from_file(ip_or_host.to_owned(), &backup_resolver) {
             Ok(x) => ips.extend(x),
-            _ => match parse_to_ip(ip_or_host.to_owned(), &resolver) {
+            _ => match parse_to_ip(ip_or_host.to_owned(), &backup_resolver) {
                 Ok(x) => ips.extend(x),
                 _ => {
```
[the remark this answers is not in the document]
Comment (shahar481) [reply src/main.rs:224]: Yeah you are absolutely right. But I think this PR is not the place for this change. I'll refactor the dns resolving part of this PR. Afterwards I'll make a new PR where I will refactor all the match expressions and improve the overall style of the code. 

Would love to hear your thoughts on this. If you disagree I can add all that to this PR.

[the remark this answers is not in the document]
Comment (niklasmohrin) [reply src/main.rs:224]: It's up to you. I think it would be nice to not merge a PR with any "new" clippy warnings / clippy warnings that are on the diff, but you sure don't have to include these fixes here. The middle way would be to have one commit that introduces the DNS stuff and a second one that cleans up the diff, but it sure is your decision.

**Comment by niklasmohrin** [comment]
@shahar481 Some PRs just went live, so you won't have to do most of these chores. Please still consider doing the rest of them 😄

**Comment by shahar481** [comment]
@niklasmohrin I think I fixed all the problems. Feel free to point out more random things to fix if you see any :)

File: src/main.rs [hunk 3]
```diff
@@ -274,18 +274,27 @@ fn parse_address(address: &str, resolver: &Resolver) -> Vec<IpAddr> {
...
-fn resolve_ips_from_host(source: &str, resolver: &Resolver) -> Vec<IpAddr> {
-    resolver
-        .lookup_ip(source)
-        .map(|x| x.iter().collect())
-        .unwrap_or_default()
+fn resolve_ips_from_host(source: &str, backup_resolver: &Resolver) -> Vec<IpAddr> {
+    let mut ips: Vec<std::net::IpAddr> = Vec::new();
+
+    if let Ok(addrs) = source.to_socket_addrs() {
+        for ip in addrs.into_iter() {
```
Comment (niklasmohrin) [inline src/main.rs:281]:
```suggestion
        for ip in addrs {
```

File: src/main.rs [hunk 4]
```diff
@@ -274,18 +274,27 @@ fn parse_address(address: &str, resolver: &Resolver) -> Vec<IpAddr> {
...
+            ips.push(ip.ip());
+        }
+    } else if let Ok(addrs) = backup_resolver.lookup_ip(&source) {
+        for ip in addrs.iter() {
+            ips.push(ip);
+        }
```
Comment (niklasmohrin) [inline src/main.rs:287]: Here you can just use `.extend()`

**Review by niklasmohrin — COMMENTED** [review]
You were right, it's just small things again :) The rest looks good :+1:

**Comment by shahar481** [comment]
Added the changes from the CR :)

**Comment by niklasmohrin** [comment]
@shahar481 Looks great! Very concise PR overall :+1:

**Review by bee-san — APPROVED** [review]

**Comment by bee-san** [comment]
@all-contributors please add @shahar481 for code
